# Created via `conda env export`. Does not include some things I did install via pip
# (e.g. hong2p), so I also created pip_exact_requirements.txt from `pip freeze`.
name: suite2p
channels:
  - numba
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alsa-lib=1.2.3=h516909a_0
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h48d8840_2
  - expat=2.4.1=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - h5py=2.10.0=nompi_py38h9915d05_106
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - jbig=2.1=h7f98852_2003
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.78.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libglib=2.68.3=h3e27bee_0
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - llvmlite=0.37.0rc2=py38hf484d3e_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.4.3=py38h578d9bd_0
  - matplotlib-base=3.4.3=py38hf4fb855_0
  - mkl=2021.3.0=h726a3e6_557
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - ncurses=6.2=h58526e2_4
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numba=0.54.0rc3=np1.11py3.8h04863e7_gc7d5f684a_0
  - numpy=1.20.3=py38h9894fe3_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.3.1=py38h8e6f84c_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - scikit-learn=0.24.2=py38h1561384_1
  - scipy=1.7.1=py38h56a6a73_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_0
  - tbb=2021.1.1=intel_119
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tk=8.6.10=h21135ba_1
  - tornado=6.1=py38h497a2fe_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - attrs==21.2.0
    - backcall==0.2.0
    - bcrypt==3.2.0
    - bottleneck==1.3.4
    - cellpose==2.0.5
    - cffi==1.14.6
    - cftime==1.6.0
    - charset-normalizer==2.1.0
    - click==7.1.2
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - cryptography==3.4.7
    - dask==2022.4.0
    - decorator==5.0.9
    - docutils==0.17.1
    - fastremap==1.12.2
    - fsspec==2022.3.0
    - gitdb==4.0.7
    - gitpython==3.1.18
    - hdmf==3.1.1
    - idna==3.3
    - ijroi==0.4.1.dev0
    - imagecodecs==2022.2.22
    - importlib-metadata==4.6.4
    - iniconfig==1.1.1
    - ipdb==0.13.9
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jsonschema==3.2.0
    - line-profiler==3.5.0
    - locket==0.2.1
    - matplotlib-inline==0.1.2
    - memory-profiler==0.60.0
    - mypy==0.910
    - mypy-extensions==0.4.3
    - natsort==7.1.1
    - opencv-python-headless==4.5.5.64
    - packaging==21.0
    - pandas==1.3.1
    - paramiko==2.7.2
    - parso==0.8.2
    - partd==1.2.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==1.0.0
    - prompt-toolkit==3.0.19
    - properscoring==0.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - py==1.10.0
    - pycparser==2.20
    - pydantic==1.8.2
    - pygments==2.9.0
    - pynacl==1.4.0
    - pynwb==2.0.0
    - pyqt5==5.15.4
    - pyqt5-plugins==5.15.4.2.2
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyqt5-tools==5.15.4.3.2
    - pyqtgraph==0.12.2
    - pyrsistent==0.18.0
    - pytest==6.2.5
    - python-dotenv==0.19.0
    - pytz==2021.1
    - pyyaml==5.4.1
    - qt5-applications==5.15.2.2.2
    - qt5-tools==5.15.2.1.2
    - rastermap==0.1.3
    - requests==2.28.1
    - ruamel-yaml==0.17.10
    - ruamel-yaml-clib==0.2.6
    - sbxreader==0.1.7
    - scanimage-tiff-reader==1.4.1
    - seaborn==0.11.1
    - smmap==4.0.0
    - termcolor==1.1.0
    - tifffile==2021.8.8
    - toml==0.10.2
    - toolz==0.11.2
    - torch==1.9.0
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - urllib3==1.26.11
    - wcwidth==0.2.5
    - xarray==0.19.0
    - xhistogram==0.3.1
    - zipp==3.5.0
prefix: /home/tom/anaconda3/envs/suite2p
